# Generated by Django 3.1.3 on 2023-03-22 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Turfs',
        ),
    ]
