# Generated by Django 3.1.3 on 2023-03-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0002_auto_20230322_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turfs',
            name='date',
        ),
        migrations.RemoveField(
            model_name='turfs',
            name='time',
        ),
        migrations.AddField(
            model_name='turfs',
            name='booked',
            field=models.IntegerField(default=1),
        ),
    ]
