"""empty message

Revision ID: 206ed71194ef
Revises: faf14abe62d6
Create Date: 2023-03-30 16:46:09.836389

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '206ed71194ef'
down_revision = 'faf14abe62d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turf', sa.Column('booked', sa.Integer(), nullable=True))
    op.drop_column('turf', 'date')
    op.drop_column('turf', 'time')
    op.add_column('turf_user', sa.Column('date', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turf_user', 'date')
    op.add_column('turf', sa.Column('time', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('turf', sa.Column('date', sa.DATE(), nullable=True))
    op.drop_column('turf', 'booked')
    # ### end Alembic commands ###
